apiVersion: v1
kind: Service
metadata:
  name: dbx-public
  labels:
    app: dbx-orchestrator
    app.kubernetes.io/name: '{{ include "dbx.name" . }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
spec:
  type: '{{ .Values.service.type }}'
  ports:
  - port: {{ .Values.service.port }}
    name: http
    targetPort: 8000
  - port: 6380
    name: resp
    targetPort: 6380
  selector:
    app: dbx-orchestrator
---
apiVersion: v1
kind: Service
metadata:
  name: dbx-internal
  labels:
    app: dbx-orchestrator
    app.kubernetes.io/name: '{{ include "dbx.name" . }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
spec:
  clusterIP: None
  ports:
  - port: 8000
    name: http
    targetPort: 8000
  selector:
    app: dbx-orchestrator
