apiVersion: v1
kind: ServiceAccount
metadata:
  name: dbx-orchestrator-sa
  labels:
    app: dbx-orchestrator
    app.kubernetes.io/name: '{{ include "dbx.name" . }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
