name: Lint
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  golangci:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24"
      - name: Build Dashboard Frontend
        working-directory: dashboard
        run: |
          npm install
          npm run build
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.5.0
          args: --timeout=5m

  eslint:
    name: Frontend Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: dashboard/package-lock.json
      - name: Install & Lint
        working-directory: dashboard
        run: |
          npm install
          npm run lint

  flake8:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install Flake8 & Black
        run: |
          pip install flake8 black
          flake8 .
          black --check .
